export const DEFAULT_SETUP_DATA: {
  group_name: string;
  key_name: string;
  value: Record<string, any> | any[];
}[] = [
  {
    group_name: "Website General",
    key_name: "general",
    value: {
      site_title: "",
      site_tagline: "Your own business website",
      admin_email: "",
      language: "en",
      site_visibility: "live",
      time_format: "h:i:s A",
      currency_position: "right",
      number_of_decimals: 2,
      thousand_separator: ",",
      decimal_separator: ".",
      date_format: "d M Y",
    },
  },
  {
    group_name: "Website Layout",
    key_name: "header_section",
    value: {
      header_top: {
        layout: "grid-cols-3",
        content: {
          left: { type: "news_ticker", items: [], status: false },
          center: { status: false, items: [], type: "text" },
          right: { type: "buttons", items: [], status: false },
        },
        status: false,
      },
      header_main: {
        content: {
          action_buttons: {
            cart: { status: true, icon: "cart" },
            wishlist: { status: true, icon: "wishlist" },
            account: { status: true, icon: "account" },
          },
          menu: { items: [] },
          search: {
            placeholder: "Search Product....",
            status: true,
            suggestions: true,
          },
          logo: { src: "", width: 150, height: 50, status: false },
        },
        status: true,
        site_title: { status: true, text: "" },
      },
      header_bottom: {
        type: "selected_menu",
        mobile_menu: { toggle_icon: "bars", status: true },
        menu_id: "main-menu",
        status: false,
        sticky: true,
      },
    },
  },
  {
    group_name: "Website Layout",
    key_name: "hero_section",
    value: {
      status: true,
      slides: [],
      layout: "split",
      autoplay: true,
      interval: 5000,
      split_layout: { side_menu_position: "left", side_menu_width: 25 },
      banner: { image: "", title: "", subtitle: "", text_position: "left" },
    },
  },
  {
    group_name: "Website Layout",
    key_name: "sections",
    value: [
      {
        id: `section-${Date.now()}`,
        type: "category_grid",
        title: "Categories",
        title_bn: "",
        status: true,
        layout: "grid",
        columns: 6,
        categoryids: [],
        grid_columns: 6,
        show_images: true,
      },
      {
        id: `section-${Date.now() + 1}`,
        type: "featured_products",
        title: "Featured Products",
        title_bn: "",
        status: true,
        layout: "grid",
        columns: 4,
        categoryids: [],
        padding: "p-0",
        margin: "mb-8",
        border_radius: "rounded-none",
      },
      {
        id: `section-${Date.now() + 2}`,
        type: "featured_brands",
        title: "Brands",
        title_bn: "",
        status: true,
        layout: "slider",
        columns: 4,
        categoryids: [],
        bg_color: "#FFFFFF",
        text_color: "#000000",
        padding: "p-0",
        margin: "mb-0",
        border_radius: "rounded-lg",
        brands: [],
      },
    ],
  },
  {
    group_name: "Website Layout",
    key_name: "footer_section",
    value: {
      status: true,
      boxes: [
        {
          id: `box-${Date.now()}`,
          type: "about",
          title: "About",
          title_bn: "",
          status: true,
          logo: "",
          content: "",
        },
        {
          id: `box-${Date.now() + 1}`,
          type: "menu",
          title: "Support",
          title_bn: "",
          status: true,
          items: [
            { label: "FAQs", label_bn: "", link: "/faq" },
            { label: "Returns Policy", label_bn: "", link: "/returns" },
          ],
        },
        {
          id: `box-${Date.now() + 2}`,
          type: "social",
          title: "Social Links",
          title_bn: "",
          status: true,
          items: [],
        },
      ],
      copyright: {
        status: true,
        show_year: true,
        text: "© {year} All rights reserved.",
        text_bn: "",
      },
      payment_methods: { status: false, methods: [] },
    },
  },
  {
    group_name: "Website Design",
    key_name: "colors",
    value: {
      primary: "#222524",
      secondary: "#DA291C",
      accent: "#F68B1E",
      background: "#ffffff",
      text: "#222524",
      heading: "#111827",
      link: "#006747",
      footer_bg: "#222524",
      footer_text: "#F3F4F6",
      sale_badge: "#DA291C",
      new_badge: "#006747",
      discount_badge: "#F68B1E",
    },
  },
  {
    group_name: "Website Design",
    key_name: "typography",
    value: {
      font_family: "Inter, sans-serif",
      heading_font: "Poppins, sans-serif",
      bangla_font: "Hind Siliguri",
      english_font: "Poppins",
      base_font_size: "16px",
      h1_size: "36px",
      h2_size: "30px",
      h3_size: "24px",
    },
  },
  {
    group_name: "E-commerce",
    key_name: "product_section",
    value: {
      status: true,
      filter_options: ["category", "price_range", "brand", "rating"],
      price_ranges: [{ min: 0, max: 50000, label: "Price Range" }],
      show_pagination: true,
      sort_options: [],
    },
  },
  {
    group_name: "E-commerce",
    key_name: "product_card",
    value: {
      layout: "minimal",
      show_title: true,
      show_price: true,
      show_rating: true,
      show_add_to_cart: true,
      show_wishlist: true,
      show_compare: false,
      show_sale_badge: true,
      show_new_badge: true,
      quick_view: true,
      show_buy_now: true,
      show_sku: false,
      show_stock: true,
      show_category: true,
      image_aspect_ratio: "square",
      show_out_of_stock_badge: true,
      show_discount_badge: true,
      primary_button: "add_to_cart",
      button_position: "bottom",
      button_size: "md",
      button_style: "icon",
      add_to_cart_text: "Add to Cart",
      buy_now_text: "Buy Now",
    },
  },
  {
    group_name: "E-commerce",
    key_name: "payment",
    value: {
      enable_review: {
        status: true,
        require_login: true,
        moderate_reviews: false,
      },
      online_payment: {
        gateways: [],
        status: false,
        success_url: "/payment/success",
        fail_url: "/payment/fail",
        ipn_url: "/payment/ipn",
        cancel_url: "/payment/cancel",
      },
      cash_on_delivery: { status: true },
    },
  },
];
